### PR TITLE
Add support for Symfony 4

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
@fitn @jmleroux any chance to get this merged at some point ?

Note that the CI failure is related to the compat with PHPUnit 6+, not to Symfony 4 (Travis pre-installed PHPUnit version uses PHPUnit 6 on PHP 7). I might send a PR fixing that, but only if you tell me there is still an interest into getting it merged.

**Review by jmleroux — APPROVED** [review]

**Comment by jmleroux** [comment]
> I might send a PR fixing that, but only if you tell me there is still an interest into getting it merged.
Thx @stof , and sorry for the delay.
What do you think about fixing the Travis in this PR?
If it s green, i'll merge it.

**Comment by stof** [comment]
@jmleroux done.

**Comment by jmleroux** [comment]
And it's done.
Released in v1.3.0.

Please also note that we are thinking about archiving/deprecating this repo and transfer ownership, to FoA organisation for instance. The decision is not totally clear right now and we will keep you updated ASAP.

**Pull request merged**
